// all constants are defined here

export const caduConstants = {
    SYNC_VAL: "00011010110011111111110000011101",
    RHCP_VAL: "000101",
    SP_POINTER_OVERFLOW_VAL: "11111111111",
    VR_CH_FRAME_CNT_MAX: 16777215,
    REPLAY_FLAG_VAL: "0",
    VR_CH_FRAME_CNT_USAGE_FLAG_VAL: "1",
    RSVD_SPARE_VAL: "00",
    VR_CH_FRAME_CNT_CYCLE_MAX: 15,
    PACKET_QUEUE_CAPACITY: 250,
    CADU_REQUESTS_CAPACITY: 50,
};

export const spacePacketConstants = {
    PRIMARY_HEADER_LEN: 6*8,
    SECONDARY_HEADER_LEN: 8*8,
    USER_DATA_FIELD_MAX_LEN: 16376*8, // 16376 bytes includes the CRC
    CRC_LEN: 4*8,
    VERSION_1_VAL: "000",
    GENERIC_PACKET_TYPE: "00000",
    TYPE_VAL: "0",
    SECONDARY_HEADER_FLAG_VAL: "1",
    SEQUENCE_COUNT_MAX: 16383,
    GRB_VERSION_VAL: "00000",
};

export const genericDataConstants = {
    GENERIC_HEADER_LEN: 21*8, // bits
    PACKET_QUEUE_CAPACITY: 100,
};

export const apids = {
    X_RAY_META_APID: 898,
    X_RAY_DATA_APID: 899,
    PROTON_LOW_META_APID: 1040,
    PROTON_LOW_DATA_APID: 1041,
    PROTON_MED_HI_META_APID: 1056,
    PROTON_MED_HI_DATA_APID: 1057,
    SOLAR_GALACTIC_PROTON_APID: 1073,
};

export const caduFields = {
    fields: [
        {name: "sync", dataType: "bitString", size: 32, bitOffset: 0},
        {aosTransferFrame: {
            fields: [
                {primaryHeader: {
                    fields: [
                        {masterChannelId: {
                            fields: [
                                {name: "transferFrameVersionNumber",
                                    dataType: "bitString", size: 2, bitOffset: 0},
                                {name: "spacecraftId",
                                    dataType: "bitString", size: 8, bitOffset: 2},
                            ],
                            size: 10, bitOffset: 0},
                        },
                        {name: "virtualChannelId", dataType: "bitString",
                            size: 6, bitOffset: 10},
                        {name: "virtualChannelFrameCount", dataType: "integer",
                            size: 24, bitOffset: 16},
                        {signalingField: {
                            fields: [
                                {name: "replayFlag",
                                    dataType: "bitString", size: 1, bitOffset: 0},
                                {name: "virtualChannelFrameCountUsageFlag",
                                    dataType: "bitString", size: 1, bitOffset: 1},
                                {name: "rsvdSpare",
                                    dataType: "bitString", size: 2, bitOffset: 2},
                                {name: "virtualChannelFrameCountCycle",
                                    dataType: "integer", size: 4, bitOffset: 4},
                            ],
                            size: 8, bitOffset: 40},
                        },
                    ],
                    size: 48, bitOffset: 0},
                },
                {dataField: {
                    fields: [
                        {mPduHeader: {
                            fields: [
                                {name: "rsvdSpare",
                                    dataType: "bitString", size: 5, bitOffset: 0},
                                {name: "firstHeaderPointer",
                                    dataType: "bitString", size: 11, bitOffset: 5},
                            ],
                            size: 16, bitOffset: 0}},
                        {name: "mPduPacketZone",
                            dataType: "bitString", size: 2034*8, bitOffset: 16},
                    ],
                    size: 2036*8, bitOffset: 48},
                },
                {name: "frameError_cf", dataType: "bitString",
                    size: 16, bitOffset: 2042*8},
            ],
            size: 2044*8, bitOffset: 32},
        },
    ],
    size: 2048*8, bitOffset: 0,
};

export const spacePacketFields = {
    primaryHeaderFields: [
        {name: "versionNum", dataType: "bitString", size: 3, bitOffset: 0},
        {name: "type", dataType: "bitString", size: 1, bitOffset: 3},
        {name: "secondaryHeaderFlag", dataType: "bitString", size: 1, bitOffset: 4},
        {name: "apid", dataType: "integer", size: 11, bitOffset: 5},
        {name: "sequenceFlag", dataType: "bitString", size: 2, bitOffset: 16},
        {name: "sequenceCount", dataType: "integer", size: 14, bitOffset: 18},
        {name: "dataLength", dataType: "integer", size: 16, bitOffset: 32},
    ],
    secondaryHeaderFields: [
        {name: "daysSinceEpoch", dataType: "integer", size: 16, bitOffset: 0},
        {name: "millisecondsOfDay", dataType: "integer", size: 32, bitOffset: 16},
        {name: "grbVersion", dataType: "bitString", size: 5, bitOffset: 48},
        {name: "grbPayloadVariant", dataType: "bitString", size: 5, bitOffset: 53},
        {name: "assemblerId", dataType: "bitString", size: 2, bitOffset: 58},
        {name: "systemEnv", dataType: "bitString", size: 4, bitOffset: 60},
    ],
};

export const genericPayloadFields = [
    {name: "compressAlgo", dataType: "bitString", size: 8, bitOffset: 0},
    {name: "secEpoch", dataType: "integer", size: 32, bitOffset: 8},
    {name: "microSec", dataType: "integer", size: 32, bitOffset: 40},
    {name: "reserved", dataType: "bitString", size: 64, bitOffset: 72},
    {name: "dataUnitSeqCount", dataType: "integer", size: 32, bitOffset: 136},
];

export const midHiProtonDataFields = [
    {name: "DiffElectronFluxes_cf", dataType: "uint64", size: 16, byteOffset: 0},
    {name: "DiffElectronFluxes", dataType: "float32", size: 200, byteOffset: 16},
    {name: "IntgElectronFluxes_cf", dataType: "uint64", size: 8, byteOffset: 216},
    {name: "IntgElectronFluxes", dataType: "float32", size: 20, byteOffset: 224},
    {name: "DiffProtonFluxes_cf", dataType: "uint64", size: 16, byteOffset: 244},
    {name: "DiffProtonFluxes", dataType: "float32", size: 220, byteOffset: 260},
    {name: "DiffElectronUncertainties_cf", dataType: "uint64", size: 16, byteOffset: 480},
    {name: "DiffElectronUncertainties", dataType: "float32", size: 200, byteOffset: 496},
    {name: "IntgElectronUncertainties_cf", dataType: "uint64", size: 8, byteOffset: 696},
    {name: "IntgElectronUncertainties", dataType: "float32", size: 20, byteOffset: 704},
    {name: "DiffProtonUncertainties_cf", dataType: "uint64", size: 16, byteOffset: 724},
    {name: "DiffProtonUncertainties", dataType: "float32", size: 220, byteOffset: 740},
    {name: "DiffElectronFluxDQFs_cf", dataType: "uint64", size: 16, byteOffset: 960},
    {name: "DiffElectronFluxDQFs", dataType: "uint8", size: 50, byteOffset: 976},
    {name: "DiffProtonFluxDQFs_cf", dataType: "uint64", size: 16, byteOffset: 1026},
    {name: "DiffProtonFluxDQFs", dataType: "uint8", size: 55, byteOffset: 1042},
    {name: "IntgElectronFluxDQFs_cf", dataType: "uint64", size: 8, byteOffset: 1097},
    {name: "IntgElectronFluxDQFs", dataType: "uint8", size: 5, byteOffset: 1105},
    {name: "Dos1_HiLetDose", dataType: "float32", size: 4, byteOffset: 1110},
    {name: "Dos1_HiLetDqf", dataType: "uint8", size: 1, byteOffset: 1114},
    {name: "Dos2_HiLetDose", dataType: "float32", size: 4, byteOffset: 1115},
    {name: "Dos2_HiLetDqf", dataType: "uint8", size: 1, byteOffset: 1119},
    {name: "Dos1_LoLetDose", dataType: "float32", size: 4, byteOffset: 1120},
    {name: "Dos1_LoLetDqf", dataType: "uint8", size: 1, byteOffset: 1124},
    {name: "Dos2_LoLetDose", dataType: "float32", size: 4, byteOffset: 1125},
    {name: "Dos2_LoLetDqf", dataType: "uint8", size: 1, byteOffset: 1129},
    {name: "L1a_EngData_Flag", dataType: "uint8", size: 1, byteOffset: 1130},
    {name: "L1a_ProtonData_Flag", dataType: "uint8", size: 1, byteOffset: 1131},
    {name: "L1a_EleData_Flag", dataType: "uint8", size: 1, byteOffset: 1132},
    {name: "L1a_DosData_Flag", dataType: "uint8", size: 1, byteOffset: 1133},
    {name: "L1b_Processing_Flag", dataType: "uint8", size: 1, byteOffset: 1134},
    {name: "N_blocks", dataType: "uint8", size: 1, byteOffset: 1135},
    {name: "Instrument_Mode", dataType: "uint8", size: 1, byteOffset: 1136},
    {name: "Instrument_Serial_Number", dataType: "uint8", size: 1, byteOffset: 1137},
    {name: "L1a_SciData_TimeStamp", dataType: "float64", size: 8, byteOffset: 1138},
    {name: "quaternion_Q0", dataType: "float32", size: 4, byteOffset: 1146},
    {name: "quaternion_Q1", dataType: "float32", size: 4, byteOffset: 1150},
    {name: "quaternion_Q2", dataType: "float32", size: 4, byteOffset: 1154},
    {name: "quaternion_Q3", dataType: "float32", size: 4, byteOffset: 1158},
    {name: "ecef_x", dataType: "float32", size: 4, byteOffset: 1162},
    {name: "ecef_y", dataType: "float32", size: 4, byteOffset: 1166},
    {name: "ecef_z", dataType: "float32", size: 4, byteOffset: 1170},
    {name: "yaw_flip_flag", dataType: "uint8", size: 1, byteOffset: 1174},
    {name: "eclipse_flag", dataType: "uint8", size: 1, byteOffset: 1175},
    {name: "solar_array_current_cf", dataType: "uint64", size: 8, byteOffset: 1176},
    {name: "solar_array_current", dataType: "uint16", size: 8, byteOffset: 1184},
];

export const lowProtonDataFields = [
    {name: "DiffElectronFluxes_cf",
        dataType: "uint64", size: 16, byteOffset: 0},
    {name: "DiffElectronFluxes", dataType: "float32", size: 840, byteOffset: 16},
    {name: "DiffElectronFluxDQFs_cf",
        dataType: "uint64", size: 16, byteOffset: 856},
    {name: "DiffElectronFluxDQFs",
        dataType: "uint8", size: 210, byteOffset: 872},
    {name: "DiffIonFluxes_cf",
        dataType: "uint64", size: 16, byteOffset: 1082},
    {name: "DiffIonFluxes", dataType: "float32", size: 840, byteOffset: 1098},
    {name: "DiffIonFluxDQFs_cf",
        dataType: "uint64", size: 16, byteOffset: 1938},
    {name: "DiffIonFluxDQFs", dataType: "uint8",
        size: 210, byteOffset: 1954},
    {name: "DiffElectronUncertainties_cf",
        dataType: "uint64", size: 16, byteOffset: 2164},
    {name: "DiffElectronUncertainties", dataType: "float32", size: 840, byteOffset: 2180},
    {name: "DiffIonUncertainties_cf",
        dataType: "uint64", size: 16, byteOffset: 3020},
    {name: "DiffIonUncertainties",
        dataType: "float32", size: 840, byteOffset: 3036},
    {name: "L1a_EngData_Flag", dataType: "uint8", size: 1, byteOffset: 3876},
    {name: "L1a_IonData_Flag", dataType: "uint8", size: 1, byteOffset: 3877},
    {name: "L1a_EleData_Flag", dataType: "uint8", size: 1, byteOffset: 3878},
    {name: "L1b_Processing_Flag", dataType: "uint8", size: 1, byteOffset: 3879},
    {name: "N_blocks", dataType: "uint8", size: 1, byteOffset: 3880},
    {name: "Instrument_Mode", dataType: "uint8", size: 1, byteOffset: 3881},
    {name: "Instrument_Serial_Number", dataType: "uint8", size: 1, byteOffset: 3882},
    {name: "L1a_SciData_TimeStamp", dataType: "float64", size: 8, byteOffset: 3883},
    {name: "quaternion_Q0", dataType: "float32", size: 4, byteOffset: 3891},
    {name: "quaternion_Q1", dataType: "float32", size: 4, byteOffset: 3895},
    {name: "quaternion_Q2", dataType: "float32", size: 4, byteOffset: 3899},
    {name: "quaternion_Q3", dataType: "float32", size: 4, byteOffset: 3903},
    {name: "ecef_x", dataType: "float32", size: 4, byteOffset: 3907},
    {name: "ecef_y", dataType: "float32", size: 4, byteOffset: 3911},
    {name: "ecef_z", dataType: "float32", size: 4, byteOffset: 3915},
    {name: "yaw_flip_flag", dataType: "uint8", size: 1, byteOffset: 3919},
    {name: "eclipse_flag", dataType: "uint8", size: 1, byteOffset: 3920},
    {name: "solar_array_current_1", dataType: "uint16", size: 8, byteOffset: 3921},
    {name: "solar_array_current_2", dataType: "uint16", size: 8, byteOffset: 3929},
];

export const xRayDataFields = [
    {name: "irradiance_xrsa1", dataType: "float32", size: 4, byteOffset: 0},
    {name: "irradiance_xrsa2", dataType: "float32", size: 4, byteOffset: 4},
    {name: "primary_xrsa", dataType: "uint8", size: 1, byteOffset: 8},
    {name: "irradiance_xrsb1", dataType: "float32", size: 4, byteOffset: 9},
    {name: "irradiance_xrsb2", dataType: "float32", size: 4, byteOffset: 13},
    {name: "primary_xrsb", dataType: "uint8", size: 1, byteOffset: 17},
    {name: "xrs_ratio", dataType: "float32", size: 4, byteOffset: 18},
    {name: "corrected_current_xrsa_1", dataType: "float32", size: 4, byteOffset: 22},
    {name: "corrected_current_xrsa_2", dataType: "float32", size: 4, byteOffset: 26},
    {name: "corrected_current_xrsa_3", dataType: "float32", size: 4, byteOffset: 30},
    {name: "corrected_current_xrsa_4", dataType: "float32", size: 4, byteOffset: 34},
    {name: "corrected_current_xrsb_1", dataType: "float32", size: 4, byteOffset: 38},
    {name: "corrected_current_xrsb_2", dataType: "float32", size: 4, byteOffset: 42},
    {name: "corrected_current_xrsb_3", dataType: "float32", size: 4, byteOffset: 46},
    {name: "corrected_current_xrsb_4", dataType: "float32", size: 4, byteOffset: 50},
    {name: "dispersion_angle", dataType: "float32", size: 4, byteOffset: 54},
    {name: "crossdispersion_angle", dataType: "float32", size: 4, byteOffset: 58},
    {name: "sc_power_side", dataType: "uint8", size: 1, byteOffset: 62},
    {name: "exis_flight_model", dataType: "uint8", size: 1, byteOffset: 63},
    {name: "exis_configuration_id", dataType: "uint16", size: 2, byteOffset: 64},
    {name: "xrs_runctrlmd", dataType: "uint8", size: 1, byteOffset: 66},
    {name: "integration_time", dataType: "float32", size: 4, byteOffset: 67},
    {name: "exs_sl_pwr_ena", dataType: "uint8", size: 1, byteOffset: 71},
    {name: "asic1_temperature", dataType: "float32", size: 4, byteOffset: 72},
    {name: "asic2_temperature", dataType: "float32", size: 4, byteOffset: 76},
    {name: "invalid_flags", dataType: "uint8", size: 1, byteOffset: 80},
    {name: "xrs_det_chg", dataType: "uint32", size: 4, byteOffset: 81},
    {name: "xrs_mode", dataType: "uint8", size: 1, byteOffset: 85},
    {name: "sps_obs_time_cf", dataType: "uint64", size: 8, byteOffset: 86},
    {name: "sps_obs_time", dataType: "float64", size: 32, byteOffset: 94},
    {name: "sps_int_time", dataType: "uint64", size: 8, byteOffset: 126},
    {name: "sps_int_time_values", dataType: "float32", size: 16, byteOffset: 134},
    {name: "sps_temperature", dataType: "uint64", size: 8, byteOffset: 150},
    {name: "sps_temperature_values", dataType: "float32", size: 16, byteOffset: 158},
    {name: "sps_det_chg", dataType: "uint64", size: 8, byteOffset: 174},
    {name: "sps_det_chg_values", dataType: "uint32", size: 16, byteOffset: 182},
    {name: "num_angle_pairs", dataType: "uint16", size: 2, byteOffset: 198},
    {name: "yaw_flip_flag", dataType: "uint8", size: 1, byteOffset: 200},
    {name: "au_factor", dataType: "float32", size: 4, byteOffset: 201},
    {name: "quality_flags", dataType: "uint32", size: 4, byteOffset: 205},
    {name: "time", dataType: "float64", size: 8, byteOffset: 209},
    {name: "packet_count", dataType: "uint32", size: 4, byteOffset: 217},
    {name: "fov_unknown", dataType: "uint8", size: 1, byteOffset: 221},
    {name: "fov_eclipse", dataType: "uint8", size: 1, byteOffset: 222},
    {name: "fov_lunar_transit", dataType: "uint8", size: 1, byteOffset: 223},
    {name: "fov_planet_transit", dataType: "uint8", size: 1, byteOffset: 224},
    {name: "fov_off_point", dataType: "uint8", size: 1, byteOffset: 225},
    {name: "quaternion_q0", dataType: "float32", size: 4, byteOffset: 226},
    {name: "quaternion_q1", dataType: "float32", size: 4, byteOffset: 230},
    {name: "quaternion_q2", dataType: "float32", size: 4, byteOffset: 234},
    {name: "quaternion_q3", dataType: "float32", size: 4, byteOffset: 238},
    {name: "ecef_x", dataType: "float32", size: 4, byteOffset: 242},
    {name: "ecef_y", dataType: "float32", size: 4, byteOffset: 246},
    {name: "ecef_z", dataType: "float32", size: 4, byteOffset: 250},
    {name: "solar_array_current_cf", dataType: "uint64", size: 8, byteOffset: 254},
    {name: "solar_array_current", dataType: "uint16", size: 8, byteOffset: 262},
    {name: "SC_eclipse_flag", dataType: "uint8", size: 1, byteOffset: 270},
];

export const solarGalacticProtonDataFields = [
    {name: "T1_DifferentialProtonFluxes_cf", dataType: "uint64", size: 16, byteOffset: 0},
    {name: "T1_DifferentialProtonFluxes", dataType: "float32", size: 48, byteOffset: 16},
    {name: "T1_DifferentialProtonFluxUncertainties_cf",
        dataType: "uint64", size: 16, byteOffset: 64},
    {name: "T1_DifferentialProtonFluxUncertainties", dataType: "float32", size: 48, byteOffset: 80},
    {name: "T1_DifferentialProtonFluxDQFs_cf", dataType: "uint64", size: 16, byteOffset: 128},
    {name: "T1_DifferentialProtonFluxDQFs", dataType: "uint8", size: 12, byteOffset: 144},
    {name: "T2_DifferentialProtonFluxes_cf", dataType: "uint64", size: 16, byteOffset: 156},
    {name: "T2_DifferentialProtonFluxes", dataType: "float32", size: 16, byteOffset: 172},
    {name: "T2_DifferentialProtonFluxUncertainties_cf",
        dataType: "uint64", size: 16, byteOffset: 188},
    {name: "T2_DifferentialProtonFluxUncertainties", dataType: "float32", size: 16, byteOffset: 204},
    {name: "T2_DifferentialProtonFluxDQFs_cf", dataType: "uint64", size: 16, byteOffset: 220},
    {name: "T2_DifferentialProtonFluxDQFs", dataType: "uint8", size: 4, byteOffset: 236},
    {name: "T3_DifferentialProtonFluxes_cf", dataType: "uint64", size: 16, byteOffset: 240},
    {name: "T3_DifferentialProtonFluxes", dataType: "float32", size: 40, byteOffset: 256},
    {name: "T3_DifferentialProtonFluxUncertainties_cf",
        dataType: "uint64", size: 16, byteOffset: 296},
    {name: "T3_DifferentialProtonFluxUncertainties", dataType: "float32", size: 40, byteOffset: 312},
    {name: "T3_DifferentialProtonFluxDQFs_cf", dataType: "uint64", size: 16, byteOffset: 352},
    {name: "T3_DifferentialProtonFluxDQFs", dataType: "uint8", size: 10, byteOffset: 368},
    {name: "T3P11_IntegralProtonFlux_cf", dataType: "uint64", size: 8, byteOffset: 378},
    {name: "T3P11_IntegralProtonFlux", dataType: "float32", size: 8, byteOffset: 386},
    {name: "T3P11_IntegralProtonFluxUncertainties_cf",
        dataType: "uint64", size: 8, byteOffset: 394},
    {name: "T3P11_IntegralProtonFluxUncertainties", dataType: "float32", size: 8, byteOffset: 402},
    {name: "T3P11_IntegralProtonFluxDQFs_cf", dataType: "uint64", size: 8, byteOffset: 410},
    {name: "T3P11_IntegralProtonFluxDQFs", dataType: "uint8", size: 2, byteOffset: 418},
    {name: "L1a_EngData_Flag_cf", dataType: "uint64", size: 8, byteOffset: 420},
    {name: "L1a_EngData_Flag", dataType: "uint8", size: 2, byteOffset: 428},
    {name: "L1a_SciData_Flag_cf", dataType: "uint64", size: 8, byteOffset: 430},
    {name: "L1a_SciData_Flag", dataType: "uint8", size: 2, byteOffset: 438},
    {name: "L1b_Processing_Flag", dataType: "uint8", size: 1, byteOffset: 440},
    {name: "N_blocks_cf", dataType: "uint64", size: 8, byteOffset: 441},
    {name: "N_blocks", dataType: "uint8", size: 2, byteOffset: 449},
    {name: "Instrument_Mode_cf", dataType: "uint64", size: 8, byteOffset: 451},
    {name: "Instrument_Mode", dataType: "uint8", size: 2, byteOffset: 459},
    {name: "Instrument_Serial_Number_cf", dataType: "uint8", size: 8, byteOffset: 461},
    {name: "Instrument_Serial_Number", dataType: "uint8", size: 2, byteOffset: 469},
    {name: "Diff31_Logic_Flags_cf", dataType: "uint64", size: 16, byteOffset: 471},
    {name: "Diff31_Logic_Flags", dataType: "uint8", size: 6, byteOffset: 487},
    {name: "L1a_SciData_TimeStamp_cf", dataType: "uint64", size: 8, byteOffset: 493},
    {name: "L1a_SciData_TimeStamp", dataType: "float64", size: 16, byteOffset: 501},
    {name: "quaternion_Q0", dataType: "float32", size: 4, byteOffset: 517},
    {name: "quaternion_Q1", dataType: "float32", size: 4, byteOffset: 521},
    {name: "quaternion_Q2", dataType: "float32", size: 4, byteOffset: 525},
    {name: "quaternion_Q3", dataType: "float32", size: 4, byteOffset: 529},
    {name: "ecef_x", dataType: "float32", size: 4, byteOffset: 533},
    {name: "ecef_y", dataType: "float32", size: 4, byteOffset: 537},
    {name: "ecef_z", dataType: "float32", size: 4, byteOffset: 541},
    {name: "yaw_flip_flag", dataType: "uint8", size: 1, byteOffset: 545},
    {name: "eclipse_flag", dataType: "uint8", size: 1, byteOffset: 546},
    {name: "solar_array_current_cf", dataType: "uint16", size: 8, byteOffset: 547},
    {name: "solar_array_current", dataType: "uint16", size: 8, byteOffset: 555},
    {name: "sgps_telemetry_time_cf", dataType: "uint64", size: 8, byteOffset: 563},
    {name: "sgps_telemetry_time", dataType: "float64", size: 16, byteOffset: 571},
    {name: "sgps_sensor_temperature_cf", dataType: "uint64", size: 16, byteOffset: 587},
    {name: "sgps_sensor_temperature", dataType: "float32", size: 32, byteOffset: 603},
];
